spring:
  application:
    name: jpql-native-query
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService
    username: ecommerceUser
    password: user1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.engine.spi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.internal: DEBUG
    org.hibernate.cache: DEBUG
    org.hibernate.cache.spi: DEBUG

server:
  port: 8081